
//Add
###
POST http://localhost:5000/triage/add HTTP/1.1
Content-Type: application/json

{
    "paciente": {
        "id": "647bc2b7e7c0e11a2b51b4c1",
        "name": "Prueba",
        "rut": "Prueba"
    },
    "remitido_por": "enfermero gonzalo",
    "centro_remitente": "2001/05/20",
    "motivo_consulta": "posible contagio covid-19",
    "signos_vitales": "signos",
    "fecha_hora": "06/07/2023",
    "categorizaciones": "C3"
}

//getAll
###
GET http://localhost:5000/triage HTTP/1.1

//getOne
###
GET http://localhost:5000/triage/647fbe3f8aac040d368aade8 HTTP/1.1

//update
###
PUT  http://localhost:5000/utriage/647fbe3f8aac040d368aade8 HTTP/1.1
Content-Type: application/json

{
    "remitido_por": "enfermero pancho",
    "centro_remitente": "2001/05/20",
    "motivo_consulta": "posible contagio covid-19",
    "signos_vitales": "signos",
    "fecha_hora": "06/07/2023",
    "categorizaciones": "C3"
}


//delete
###
DELETE http://localhost:5000/deletetriage/647d2bfffab5a54ecb9bd888 HTTP/1.1